### ISSUE TITLE
InvalidSequenceTokenException: The given sequenceToken is invalid.

### ISSUE THREAD

**Issue by canadiannomad** [TheJoshuaEvans/cloudwatch-log#1]
It seems that if the logging ever fails, this library isn't able to handle recovering what the next sequenceToken is, and all future logs fail.

```
InvalidSequenceTokenException
The sequence token is not valid. You can get the correct sequence token in the expectedSequenceToken field in the InvalidSequenceTokenException message.

HTTP Status Code: 400
```

Further there should probably be some buffering, because it is easy to get `ThrottlingException: Rate exceeded` errors if you output a lot of logs (or get a lot of errors like the above..).

**Comment by TheJoshuaEvans** [comment]
Excellent catch! I am swamped with other work and probably won't be able to fix this right away. Anybody who wants to try and fix this is more than welcome to

**Comment by TheJoshuaEvans** [comment]
I have fixed this issue, the library should now recover from invalid sequence token exceptions. However, I did not have the time to add request buffering, but made a separate issue for that enhancement: https://github.com/TheJoshuaEvans/cloudwatch-log/issues/4

**Comment by TheJoshuaEvans** [comment]
BTW this PR adds buffering: https://github.com/TheJoshuaEvans/cloudwatch-log/pull/5
